version: '3'
services:
  db:
    image: mysql:8.0.23
    platform: linux/x86_64
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: apollo-server-template
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  web: &web_base
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: /bin/bash -c 'yarn dev'
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/apollo-server-template
  prismastudio:
    <<: *web_base
    command: /bin/bash -c 'yarn prisma studio'
    ports:
      - 5555:5555
