version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: /bin/ash -c 'yarn start'
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
    volumes:
      - .:/apollo-server-template
