type User {
  id: Int!
  name: String!
  email: String!
}

input UserCreateInput {
  name: String!
  email: String!
  encryptedPassword: String!
}

type Mutation {
  createUser(input: UserCreateInput!): User
}
